### ISSUE TITLE
Compatibility with Inferno v8

### ISSUE THREAD

**Issue by einar-hjortdal** [dessalines/inferno-i18next-dess#2]
Is this compatible with Inferno v8?
Thank you for publishing this on npm

**Comment by dessalines** [comment]
I'm still in the process of upgrading to inferno v8 so I haven't been able to test it yet.

**Comment by einar-hjortdal** [comment]
It looks like [nimbusec-oss](https://github.com/nimbusec-oss/inferno-i18next) updated their repo for inferno 8.0.3 and marked the commit as breaking change. I hope you can update your repo too

**Comment by dessalines** [comment]
Okay `0.0.2` is published now.
